"""Initial Migration

Revision ID: d738179b3d12
Revises: 78d07d2dd7c1
Create Date: 2022-05-15 20:19:41.613371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd738179b3d12'
down_revision = '78d07d2dd7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog', sa.Text(length=255), nullable=False),
    sa.Column('writer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['writer'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
